- name: Install Java on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Java 21 (Amazon Linux 2)
      yum:
        name: java-21-amazon-corretto-devel
        state: present

- name: create directory
  hosts: all
  become: true
  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /home/ec2-user/springboot
        state: directory
        mode: "0755"

- name: Git install and Clone
  hosts: all
  become: true
  tasks:
    - name: git install
      ansible.builtin.yum:
        name: git
        state: present

    - name: Clone a Git repository
      ansible.builtin.git:
        repo: "https://github.com/mito3103/helloworld.git"
        dest: /home/ec2-user/springboot
      when: not ansible_check_mode

    - name: Ensure gradlew is executable
      ansible.builtin.file:
        path: /home/ec2-user/springboot/demo/gradlew
        state: file
        mode: "0755"
      when: not ansible_check_mode

- name: Start SpringBoot
  hosts: all
  become: true
  tasks:
    - name: Build the JAR file
      ansible.builtin.command: ./gradlew build
      args:
        chdir: /home/ec2-user/springboot/demo
      when: not ansible_check_mode

    - name: Run Spring Boot app in background
      ansible.builtin.shell: "nohup java -jar build/libs/demo-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"
      args:
        chdir: /home/ec2-user/springboot/demo
      when: not ansible_check_mode

    # - name: Build the application using gradlew
    #   ansible.builtin.command: ./gradlew bootRun
    #   args:
    #     chdir: /home/ec2-user/springboot/demo
    #   when: not ansible_check_mode
