- name: Install Java on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Java 21 (Amazon Linux 2)
      yum:
        name: java-21-amazon-corretto-devel
        state: present

- name: create directory
  hosts: all
  become: true
  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /springboot
        state: directory
        mode: "0755"

- name: Git install and Clone
  hosts: all
  become: true
  tasks:
    - name: git install
      ansible.builtin.yum:
        name: git
        state: present

    - name: Clone a Git repository
      ansible.builtin.git:
        repo: "https://github.com/mito3103/helloworld.git"
        dest: /springboot/app
      when: not ansible_check_mode

- name: Start SpringBoot
  hosts: all
  become: true
  tasks:
    - name: Spring Boot アプリを起動
      shell: nohup java -jar demo --server.port=8080 &
