- name: Install Java on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Java 21 (Amazon Linux 2)
      yum:
        name: java-21-amazon-corretto-devel
        state: present

- name: Git install and Clone
  hosts: all
  become: true
  tasks:
    - name: git install
      ansible.builtin.yum:
        name: git
        state: present

    - name: Locate git binary
      ansible.builtin.shell: command -v git
      register: git_path

    - name: Show path to git
      ansible.builtin.debug:
        var: git_path.stdout

    - name: Clone a Git repository
      ansible.builtin.git:
        repo: "https://github.com/mito3103/helloworld.git"
        dest: /home/ec2-user
        executable: /usr/bin/git

- name: Start SpringBoot
  hosts: all
  become: true
  tasks:
    - name: Spring Boot アプリを起動
      systemd:
        name: helloworld
        state: restarted
        enabled: yes
