AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  awsstudycfkey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2の事前作成Keypair

  prefix:
    Type: String
    Default: aws-study

Resources:
  awsstudycfvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-vpc

  awsstudycfigw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-igw

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref awsstudycfvpc
      InternetGatewayId: !Ref awsstudycfigw

  awsstudycfpublicrtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsstudycfvpc
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-public-rtb

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref awsstudycfpublicrtb
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref awsstudycfigw

  awsstudycfpublicsubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: !Select [0,!GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-public-subnet1

  awsstudycfpublicsubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: !Select [1,!GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-public-subnet2

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfpublicsubnet1
      RouteTableId: !Ref awsstudycfpublicrtb

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfpublicsubnet2
      RouteTableId: !Ref awsstudycfpublicrtb


  awsstudycfrtbprivateapnortheast1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsstudycfvpc
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-rtb-private-ap-northeast-1a

  awsstudycfrtbprivateapnortheast1c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsstudycfvpc
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-rtb-private-ap-northeast-1c

  awsstudycfprivatesubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: !Select [0,!GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-private-subnet1

  awsstudycfprivatesubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: !Select [1,!GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-private-subnet2

  awsstudycfprivatesubnet1association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfprivatesubnet1
      RouteTableId: !Ref awsstudycfrtbprivateapnortheast1a


  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfprivatesubnet2
      RouteTableId: !Ref awsstudycfrtbprivateapnortheast1c

  awsstudycfec2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f95ad36d6d54ceba
      InstanceType: t2.micro
      DisableApiTermination: true
      SubnetId: !Ref awsstudycfpublicsubnet1
      SecurityGroupIds:
      - !Ref awsstudycfec2sg
      KeyName: !Ref awsstudycfkey
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-ec2

  awsstudycfec2sg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref awsstudycfvpc
      GroupDescription: ec2security
      SecurityGroupIngress:
      -   IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 111.191.60.158/32
      -   IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 111.191.60.158/32
      SecurityGroupEgress:
      -   IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-ec2-sg
