AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  awsstudycfkey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2の事前作成Keypair

  prefix:
    Type: String
    Default: aws-study
  
  DBUsername:
    Type: String
    Default: root
  
  DBMasterPassword:
    NoEcho: true
    Description: RDS master password
    Type: String

#Cloudwatchパラメータ
  Threshold: 
    Description: CPUUtilization Value
    Type: Number

#SNSパラメータ
  EndPoint:
    Description: SNS send email
    Type: String

Resources:
  awsstudycfvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-vpc

  awsstudycfigw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-igw

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref awsstudycfvpc
      InternetGatewayId: !Ref awsstudycfigw

  awsstudycfpublicrtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsstudycfvpc
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-public-rtb

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref awsstudycfpublicrtb
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref awsstudycfigw

  awsstudycfpublicsubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: !Select [0,!GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-public-subnet1

  awsstudycfpublicsubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: !Select [1,!GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-public-subnet2

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfpublicsubnet1
      RouteTableId: !Ref awsstudycfpublicrtb

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfpublicsubnet2
      RouteTableId: !Ref awsstudycfpublicrtb


  awsstudycfrtbprivateapnortheast1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsstudycfvpc
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-rtb-private-ap-northeast-1a

  awsstudycfrtbprivateapnortheast1c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref awsstudycfvpc
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-rtb-private-ap-northeast-1c

  awsstudycfprivatesubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: !Select [0,!GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-private-subnet1

  awsstudycfprivatesubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref awsstudycfvpc
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: !Select [1,!GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-private-subnet2

  awsstudycfprivatesubnet1association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfprivatesubnet1
      RouteTableId: !Ref awsstudycfrtbprivateapnortheast1a


  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref awsstudycfprivatesubnet2
      RouteTableId: !Ref awsstudycfrtbprivateapnortheast1c

  awsstudycfec2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f95ad36d6d54ceba
      InstanceType: t2.micro
      #DisableApiTermination: true
      SubnetId: !Ref awsstudycfpublicsubnet1
      SecurityGroupIds:
      - !Ref awsstudycfec2sg
      KeyName: !Ref awsstudycfkey
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-ec2

  awsstudycfec2sg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref awsstudycfvpc
      GroupDescription: ec2security
      SecurityGroupIngress:
      -   IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 111.191.60.158/32
      -   IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref awsstudycfalbsg 
      SecurityGroupEgress:
      -   IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-ec2-sg

  awsstudycfrdssg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref awsstudycfvpc
      GroupDescription: rdssecurity
      SecurityGroupIngress:
      -   IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref awsstudycfec2sg
      SecurityGroupEgress:
      -   IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-rds-sg
  
  awsstudycfalbsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref awsstudycfvpc
      GroupDescription: albsecurity
      SecurityGroupIngress:
      -   IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 111.191.60.158/32
      Tags:
      - Key: Name
        Value: !Sub ${prefix}-cf-alb-sg

  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Description of subnet group
      SubnetIds: 
        - !Ref awsstudycfprivatesubnet1
        - !Ref awsstudycfprivatesubnet2
      Tags: 
        - Key: Name
          Value: !Sub ${prefix}-cf-rds-subnetgp

  RDSMonitoringRole:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${prefix}-cf-monitoring-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  awsstudycfrds:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t4g.micro
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      AvailabilityZone: !Select [0,!GetAZs '']
      BackupRetentionPeriod: '1'
      DBInstanceIdentifier: !Sub ${prefix}-cf-rds
      DBName: awsstudy
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql
      EngineVersion: 8.0.39
      LicenseModel: general-public-license
      MasterUsername: !Ref DBUsername 
      MasterUserPassword: !Ref DBMasterPassword
      MonitoringInterval: '60'
      MonitoringRoleArn: !GetAtt RDSMonitoringRole.Arn
      EnableCloudwatchLogsExports:
        - error
        - slowquery
        - audit
        - general
      MultiAZ: false
      Port: 3306
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups: 
        - !GetAtt awsstudycfrdssg.GroupId
      Tags:
        - Key: Name
          Value: aws-study-cf-rds

  awsstudycfalb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-cf-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !Ref awsstudycfalbsg
      Subnets:
        - !Ref awsstudycfpublicsubnet1
        - !Ref awsstudycfpublicsubnet2
  
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref awsstudycfalb
      Port: 80
      Protocol: HTTP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref awsstudycftg
      
  awsstudycftg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: aws-study-cf-tg
      Protocol: HTTP
      Port: 80
      TargetType: instance
      Targets:
      - Id: !Ref awsstudycfec2
        Port: 8080
      VpcId: !Ref awsstudycfvpc
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200,300,301

##CloudWatch
  EC2CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${prefix}-cf-cpu-utilization-testalarm"
      AlarmDescription: !Sub "${prefix}-cf-ec2のCPU使用率が ${Threshold} %以上でトリガーされます" 

      ### メトリクス
      Namespace: "AWS/EC2"
      Dimensions:
        - Name: InstanceId 
          Value: !Ref awsstudycfec2
      MetricName: "CPUUtilization"
      Period: 300
      Statistic: "Average"
      Threshold: !Ref Threshold
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: "missing"
      ActionsEnabled: True
      AlarmActions:
        - !Ref awsstudycfsnsTopic

##SNSトピック・サブスク作成
  awsstudycfsnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: aws-study-cf-testalarm
      TopicName: aws-study-cf-testalarm
      Tags:
      -  Key: "Name"
         Value: "aws-study-cf-testalarm"

  snsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref awsstudycfsnsTopic
      Protocol: email 
      Endpoint: !Ref EndPoint

#WAF設定
  WebAcl:
    Type: AWS::WAFv2::WebACL
    DeletionPolicy: Delete
    Properties:
      Name: !Sub ${prefix}-cf-web-acl
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: !Sub ${prefix}-cf-web-acl 
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:      
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
  
  WAFLogConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    DeletionPolicy: Delete
    Properties:
      LogDestinationConfigs: 
        - !GetAtt LogGroup.Arn
      ResourceArn: !GetAtt WebAcl.Arn
  
  WebAclAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DeletionPolicy: Delete
    Properties:
      ResourceArn: !Ref awsstudycfalb
      WebACLArn: !GetAtt WebAcl.Arn

  WAFToCWLogsPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: WAFToCWLogsPolicy
      PolicyDocument: 
        Fn::Sub:
          - |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "delivery.logs.amazonaws.com"
                  },
                  "Action": [
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                  ],
                  "Resource": "${LogGroup}"
                }
              ]
            }
          - LogGroupArn: !GetAtt LogGroup.Arn

#ロググループの設定
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: aws-waf-logs-testlogs
      RetentionInDays: 1

