name: Terraform CI

on:
  pull_request:
    # types:
    #   - opened
    #   - synchronize
    branches: [main]
    # paths:
    #   - "**.tf"
    #   - "**.tftest.hcl"
    #   - ".github/workflows/terraform-ci.yml"

  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    defaults:
      run:
        working-directory: aws-study-tf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: AWS CLIのセットアップ
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test
