name: Terraform CD #ssh修正

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
      - "**.tftest.hcl"
      - ".github/workflows/*.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    defaults:
      run:
        working-directory: aws-study-tf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Restore tfvars from base64 secret
        run: |
          echo "${{ secrets.TFVARS_B64 }}" | base64 -d > terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

  deploy-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: AWS認証情報の設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Set up Python and Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible

      - name: セキュリティグループの更新
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id=sg-033646bf4202529c6 \
          --protocol=tcp \
          --port=22 \
          --cidr=${{ steps.ip.outputs.ipv4 }}/32 # github global ip

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-112-188-152.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory/production.yml playbook/deploy.yml

      - name: Run Java #必要？
        run: |
          ansible-playbook -i hosts run_jar.yml -u ユーザー名

      - name: セキュリティグループのルール削除
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id=sg-033646bf4202529c6 \
          --protocol=tcp \
          --port=22 \
          --cidr=${{ steps.ip.outputs.ipv4 }}/32
